# Creates a Win32 package and optionally imports into a target Intune tenant
# Uses secrets on the repo - TENANT_ID, CLIENT_ID, and CLIENT_SECRET
# to import the package into a target tenant
name: test-package

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:

jobs:
  create-package:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test for Applications.json
        id: test-appjson
        shell: powershell
        run: |
          Test-Path -Path "${{ github.workspace }}\packages\${{ github.event.inputs.configuration }}"

      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v5.0
        with:
          modules-to-cache: Evergreen, VcRedist
          shell: powershell

      # Create the app package
      - name: Authn to the Graph API and create package/s
        id: upload-package
        shell: powershell
        run: |
          $params = @{
            Path     = "${{ github.workspace }}\packages"
            Manifest = "${{ github.workspace }}\scripts\Applications.json"
          }
          . ${{ github.workspace }}\scripts\Test-Apps.ps1 @params
